export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const TOKEN_TO_STORE = "TOKEN_TO_STORE";