export const ADD_TO_CART = "ADD_TO_CART";
export const EDIT_CART = "EDIT_CART";
export const FETCH_ALL_CART_ITEMS = "FETCH_ALL_CART_ITEMS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const REMOVE_CART = "REMOVE_CART";
export const TOKEN_TO_STORE = "TOKEN_TO_STORE";